node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/boutcha/sample-spring-microservices.git', credentialsId: 'boutcha', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('discovery-service') {
                def app = docker.build "cloud.canister.io:5000/aboutchamir/discovery:${env.version}"
                app.push()
            }
        }
        /* remove runnung phase
        stage ('Run') {
            docker.image("cloud.canister.io:5000/aboutchamir/discovery:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      
        */

    }

}